version: 2
jobs:
  build:
    docker:
      - image: ghcr.io/martinthomson/i-d-template-action:latest
    working_directory: ~/draft

    steps:
      - checkout

      - run:
          name: "Check Formatting"
          command: |
            apk add black
            black --check .

      - run:
          name: "Run Tests"
          command: |
            if [ -z "$CIRCLE_TAG" ]; then
              pip3 install behave
              mkdir -p /tmp/artifacts
              behave --junit --junit-directory /tmp/artifacts tests/*.feature
            fi

      - store_artifacts:
          path: /tmp/artifacts

      - store_test_results:
          path: /tmp/artifacts


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*?/
