name: "Update Docker Image for GitHub Action"

on:
  push:
    paths:
    - "docker/**"
    - ".github/workflows/docker.yml"
  schedule:
    # Once monthly at a randomly selected time.
    - cron: "24 2 3,18 * *"

jobs:
  build:
    name: "Update Docker Image"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Get Tag"
      id: tag
      run: |
        ref="${{ github.ref }}"
        if [ "$ref" = "refs/heads/main" ]; then
          echo "::set-output name=tag::latest"
        elif [ "${ref#refs/tags/}" != "$ref" ]; then
          echo "::set-output name=tag::${ref#refs/tags/}"
        else
          echo "::set-output name=tag::test"
        fi

    - name: "Setup Docker Buildx"
      uses: docker/setup-buildx-action@v1

    - name: "Login to DockerHub"
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: "Login to GitHub Container Registry"
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PASSWORD }}

    - name: "Build and Publish"
      uses: docker/build-push-action@v2
      with:
        context: ./action
        file: ./action/Dockerfile
        push: ${{ steps.tag.outputs.tag != 'test' }}
        tags: |
          martinthomson/i-d-template-action:${{ steps.tag.outputs.tag }}
          ghcr.io/martinthomson/i-d-template-action:${{ steps.tag.outputs.tag }}
